2020-05-12 08:16:05.457 16855 INFO cinder.rpc [req-af4e7958-bc86-4634-91bd-e1bcfe4dc69d - - - - -] Automatically selected cinder-scheduler objects version 1.38 as minimum service version.
2020-05-12 08:16:05.465 16855 INFO cinder.rpc [req-af4e7958-bc86-4634-91bd-e1bcfe4dc69d - - - - -] Automatically selected cinder-scheduler RPC version 3.11 as minimum service version.
2020-05-12 08:16:05.539 16855 INFO cinder.volume.manager [req-af4e7958-bc86-4634-91bd-e1bcfe4dc69d - - - - -] Determined volume DB was empty at startup.
2020-05-12 08:16:05.546 16855 INFO cinder.volume.manager [req-af4e7958-bc86-4634-91bd-e1bcfe4dc69d - - - - -] Service not found for updating active_backend_id, assuming default for driver init.
2020-05-12 08:16:05.548 16855 WARNING stevedore.named [req-af4e7958-bc86-4634-91bd-e1bcfe4dc69d - - - - -] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager: ServiceNotFound: Service cinder-volume could not be found on host centos7@lvm.
2020-05-12 08:16:05.548 16855 WARNING castellan.key_manager [req-af4e7958-bc86-4634-91bd-e1bcfe4dc69d - - - - -] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
2020-05-12 08:16:05.549 16855 WARNING cinder.keymgr.conf_key_mgr [req-af4e7958-bc86-4634-91bd-e1bcfe4dc69d - - - - -] This key manager is insecure and is not recommended for production deployments: NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
2020-05-12 08:16:05.806 16855 INFO cinder.volume.manager [req-af4e7958-bc86-4634-91bd-e1bcfe4dc69d - - - - -] Image-volume cache disabled for host centos7@lvm.
2020-05-12 08:16:05.828 16855 INFO oslo_service.service [req-af4e7958-bc86-4634-91bd-e1bcfe4dc69d - - - - -] Starting 1 workers
2020-05-12 08:16:05.845 17117 INFO cinder.service [-] Starting cinder-volume node (version 14.0.4)
2020-05-12 08:16:05.875 16855 WARNING oslo_config.cfg [req-af4e7958-bc86-4634-91bd-e1bcfe4dc69d - - - - -] Deprecated: Option "auth_uri" from group "keystone_authtoken" is deprecated for removal (The auth_uri option is deprecated in favor of www_authenticate_uri and will be removed in the S  release.).  Its value may be silently ignored in the future.
2020-05-12 08:16:05.882 17117 INFO cinder.volume.manager [req-80f6ef10-b8a5-483f-aff3-0d6903778f31 - - - - -] Starting volume driver LVMVolumeDriver (3.0.0)
2020-05-12 08:16:06.790 17117 INFO cinder.brick.local_dev.lvm [req-80f6ef10-b8a5-483f-aff3-0d6903778f31 - - - - -] Logical Volume not found when querying LVM info. (vg_name=cinder-volumes, lv_name=cinder-volumes-pool
2020-05-12 08:16:10.577 17117 INFO cinder.volume.drivers.lvm [req-80f6ef10-b8a5-483f-aff3-0d6903778f31 - - - - -] Enabling LVM thin provisioning by default because a thin pool exists.
2020-05-12 08:16:12.302 17117 INFO cinder.keymgr.migration [req-a1436f3b-52f8-483f-b784-ca0ddc51a805 - - - - -] Not migrating encryption keys because the ConfKeyManager is still in use.
2020-05-12 08:16:13.939 17117 INFO cinder.volume.manager [req-80f6ef10-b8a5-483f-aff3-0d6903778f31 - - - - -] Driver initialization completed successfully.
2020-05-12 08:16:13.949 17117 INFO cinder.manager [req-80f6ef10-b8a5-483f-aff3-0d6903778f31 - - - - -] Initiating service 3 cleanup
2020-05-12 08:16:13.956 17117 INFO cinder.manager [req-80f6ef10-b8a5-483f-aff3-0d6903778f31 - - - - -] Service 3 cleanup completed.
2020-05-12 08:16:14.153 17117 INFO cinder.volume.manager [req-80f6ef10-b8a5-483f-aff3-0d6903778f31 - - - - -] Initializing RPC dependent components of volume driver LVMVolumeDriver (3.0.0)
2020-05-12 08:16:17.082 17117 INFO cinder.volume.manager [req-80f6ef10-b8a5-483f-aff3-0d6903778f31 - - - - -] Driver post RPC initialization completed successfully.
2020-05-12 09:08:16.289 17117 INFO cinder.rpc [req-53a0e621-5faa-440e-9d4d-55560a68c432 775220a4ac234a878bdce88c2e3678b5 973168b02ba046ec8ad7a56a4b28fb35 - default default] Automatically selected cinder-backup objects version 1.38 as minimum service version.
2020-05-12 09:08:16.300 17117 INFO cinder.rpc [req-53a0e621-5faa-440e-9d4d-55560a68c432 775220a4ac234a878bdce88c2e3678b5 973168b02ba046ec8ad7a56a4b28fb35 - default default] Automatically selected cinder-backup RPC version 2.1 as minimum service version.
2020-05-12 09:08:16.317 17117 INFO cinder.rpc [req-53a0e621-5faa-440e-9d4d-55560a68c432 775220a4ac234a878bdce88c2e3678b5 973168b02ba046ec8ad7a56a4b28fb35 - default default] Automatically selected cinder-volume objects version 1.38 as minimum service version.
2020-05-12 09:08:16.325 17117 INFO cinder.rpc [req-53a0e621-5faa-440e-9d4d-55560a68c432 775220a4ac234a878bdce88c2e3678b5 973168b02ba046ec8ad7a56a4b28fb35 - default default] Automatically selected cinder-volume RPC version 3.16 as minimum service version.
2020-05-12 09:08:16.326 17117 WARNING stevedore.named [req-53a0e621-5faa-440e-9d4d-55560a68c432 775220a4ac234a878bdce88c2e3678b5 973168b02ba046ec8ad7a56a4b28fb35 - default default] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
2020-05-12 09:08:16.327 17117 WARNING castellan.key_manager [req-53a0e621-5faa-440e-9d4d-55560a68c432 775220a4ac234a878bdce88c2e3678b5 973168b02ba046ec8ad7a56a4b28fb35 - default default] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
2020-05-12 09:08:17.197 17117 INFO cinder.volume.flows.manager.create_volume [req-53a0e621-5faa-440e-9d4d-55560a68c432 775220a4ac234a878bdce88c2e3678b5 973168b02ba046ec8ad7a56a4b28fb35 - default default] Volume ff682d50-2f29-45bd-a9ae-41a933ca5bd7: being created as image with specification: {'status': u'creating', 'image_location': (None, None), 'volume_size': 20, 'volume_name': u'volume-ff682d50-2f29-45bd-a9ae-41a933ca5bd7', 'image_id': u'33b99f7a-55ad-4205-b275-afc4fe70bd76', 'image_service': <cinder.image.glance.GlanceImageService object at 0x7fb1a5de0a10>, 'image_meta': {u'status': u'active', u'file': u'/v2/images/33b99f7a-55ad-4205-b275-afc4fe70bd76/file', u'id': u'33b99f7a-55ad-4205-b275-afc4fe70bd76', u'name': u'cirros', u'tags': [], u'container_format': u'bare', u'created_at': datetime.datetime(2020, 5, 12, 12, 20, 18, tzinfo=<iso8601.Utc>), u'disk_format': u'qcow2', u'updated_at': datetime.datetime(2020, 5, 12, 12, 20, 19, tzinfo=<iso8601.Utc>), u'visibility': u'public', u'os_hash_algo': u'sha512', u'owner': u'fe075815291f47ad953af62fa77bc900', u'protected': False, u'os_hash_value': u'507ca3ef53a49145ede39d6cb7394bb40b5f419aec5abac496880112825cf177c15f49e35ac7c8c9a45d659598b71d0c59b93d85c79c2d54c69748bdeda2b0a5', u'min_ram': 0, u'checksum': u'52ba1c45042aa3688c09f303da283524', u'min_disk': 0, u'os_hidden': False, u'virtual_size': None, 'properties': {}, u'size': 273}}
2020-05-12 09:08:17.422 17117 INFO cinder.image.image_utils [req-53a0e621-5faa-440e-9d4d-55560a68c432 775220a4ac234a878bdce88c2e3678b5 973168b02ba046ec8ad7a56a4b28fb35 - default default] Image download 0.00 MB at 0.00 MB/s
2020-05-12 09:08:20.604 17117 ERROR cinder.volume.utils [req-53a0e621-5faa-440e-9d4d-55560a68c432 775220a4ac234a878bdce88c2e3678b5 973168b02ba046ec8ad7a56a4b28fb35 - default default] Failed to copy image 33b99f7a-55ad-4205-b275-afc4fe70bd76 to volume: ff682d50-2f29-45bd-a9ae-41a933ca5bd7: ProcessExecutionError: Unexpected error while running command.
Command: sudo cinder-rootwrap /etc/cinder/rootwrap.conf qemu-img convert -O raw -t none -f qcow2 /var/lib/cinder/conversion/tmpyxMNYgcentos7@lvm /dev/mapper/cinder--volumes-volume--ff682d50--2f29--45bd--a9ae--41a933ca5bd7
Exit code: 1
Stdout: u''
Stderr: u"qemu-img: Could not open '/var/lib/cinder/conversion/tmpyxMNYgcentos7@lvm': Image is not in qcow2 format\n"
2020-05-12 09:08:20.604 17117 ERROR cinder.volume.utils Traceback (most recent call last):
2020-05-12 09:08:20.604 17117 ERROR cinder.volume.utils   File "/usr/lib/python2.7/site-packages/cinder/volume/utils.py", line 1152, in copy_image_to_volume
2020-05-12 09:08:20.604 17117 ERROR cinder.volume.utils     context, volume, image_service, image_id)
2020-05-12 09:08:20.604 17117 ERROR cinder.volume.utils   File "/usr/lib/python2.7/site-packages/cinder/volume/drivers/lvm.py", line 508, in copy_image_to_volume
2020-05-12 09:08:20.604 17117 ERROR cinder.volume.utils     size=volume['size'])
2020-05-12 09:08:20.604 17117 ERROR cinder.volume.utils   File "/usr/lib/python2.7/site-packages/cinder/image/image_utils.py", line 516, in fetch_to_raw
2020-05-12 09:08:20.604 17117 ERROR cinder.volume.utils     size=size, run_as_root=run_as_root)
2020-05-12 09:08:20.604 17117 ERROR cinder.volume.utils   File "/usr/lib/python2.7/site-packages/cinder/image/image_utils.py", line 596, in fetch_to_volume_format
2020-05-12 09:08:20.604 17117 ERROR cinder.volume.utils     run_as_root=run_as_root)
2020-05-12 09:08:20.604 17117 ERROR cinder.volume.utils   File "/usr/lib/python2.7/site-packages/cinder/image/image_utils.py", line 300, in convert_image
2020-05-12 09:08:20.604 17117 ERROR cinder.volume.utils     passphrase_file=passphrase_file)
2020-05-12 09:08:20.604 17117 ERROR cinder.volume.utils   File "/usr/lib/python2.7/site-packages/cinder/image/image_utils.py", line 244, in _convert_image
2020-05-12 09:08:20.604 17117 ERROR cinder.volume.utils     utils.execute(*cmd, run_as_root=run_as_root)
2020-05-12 09:08:20.604 17117 ERROR cinder.volume.utils   File "/usr/lib/python2.7/site-packages/cinder/utils.py", line 128, in execute
2020-05-12 09:08:20.604 17117 ERROR cinder.volume.utils     return processutils.execute(*cmd, **kwargs)
2020-05-12 09:08:20.604 17117 ERROR cinder.volume.utils   File "/usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py", line 424, in execute
2020-05-12 09:08:20.604 17117 ERROR cinder.volume.utils     cmd=sanitized_cmd)
2020-05-12 09:08:20.604 17117 ERROR cinder.volume.utils ProcessExecutionError: Unexpected error while running command.
2020-05-12 09:08:20.604 17117 ERROR cinder.volume.utils Command: sudo cinder-rootwrap /etc/cinder/rootwrap.conf qemu-img convert -O raw -t none -f qcow2 /var/lib/cinder/conversion/tmpyxMNYgcentos7@lvm /dev/mapper/cinder--volumes-volume--ff682d50--2f29--45bd--a9ae--41a933ca5bd7
2020-05-12 09:08:20.604 17117 ERROR cinder.volume.utils Exit code: 1
2020-05-12 09:08:20.604 17117 ERROR cinder.volume.utils Stdout: u''
2020-05-12 09:08:20.604 17117 ERROR cinder.volume.utils Stderr: u"qemu-img: Could not open '/var/lib/cinder/conversion/tmpyxMNYgcentos7@lvm': Image is not in qcow2 format\n"
2020-05-12 09:08:20.604 17117 ERROR cinder.volume.utils 
2020-05-12 09:08:20.621 17117 WARNING cinder.volume.manager [req-53a0e621-5faa-440e-9d4d-55560a68c432 775220a4ac234a878bdce88c2e3678b5 973168b02ba046ec8ad7a56a4b28fb35 - default default] Task 'cinder.volume.flows.manager.create_volume.CreateVolumeFromSpecTask;volume:create' (6742a7d5-7b21-426f-a497-6a0685acc07b) transitioned into state 'FAILURE' from state 'RUNNING'
5 predecessors (most recent first):
  Atom 'cinder.volume.flows.manager.create_volume.NotifyVolumeActionTask;volume:create, create.start' {'intention': 'EXECUTE', 'state': 'SUCCESS', 'requires': {'volume': Volume(_name_id=None,admin_metadata={},attach_status='detached',availability_zone='nova',bootable=False,cluster=<?>,cluster_name=None,consistencygroup=<?>,consistencygroup_id=None,created_at=2020-05-12T13:08:15Z,deleted=False,deleted_at=None,display_description='',display_name='',ec2_id=None,encryption_key_id=None,glance_metadata=<?>,group=<?>,group_id=None,host='centos7@lvm#lvm',id=ff682d50-2f29-45bd-a9ae-41a933ca5bd7,launched_at=None,metadata={},migration_status=None,multiattach=False,previous_status=None,project_id='973168b02ba046ec8ad7a56a4b28fb35',provider_auth=None,provider_geometry=None,provider_id=None,provider_location=None,replication_driver_data=None,replication_extended_status=None,replication_status=None,scheduled_at=2020-05-12T13:08:16Z,service_uuid=None,shared_targets=True,size=20,snapshot_id=None,snapshots=<?>,source_volid=None,status='downloading',terminated_at=None,updated_at=2020-05-12T13:08:16Z,user_id='775220a4ac234a878bdce88c2e3678b5',volume_attachment=<?>,volume_type=VolumeType(44cf1e15-4648-4db9-ab86-e0f80c62840f),volume_type_id=44cf1e15-4648-4db9-ab86-e0f80c62840f), 'context': <cinder.context.RequestContext object at 0x7fb1a5e01610>}, 'provides': None}
  |__Atom 'cinder.volume.flows.manager.create_volume.ExtractVolumeSpecTask;volume:create' {'intention': 'EXECUTE', 'state': 'SUCCESS', 'requires': {'volume': Volume(_name_id=None,admin_metadata={},attach_status='detached',availability_zone='nova',bootable=False,cluster=<?>,cluster_name=None,consistencygroup=<?>,consistencygroup_id=None,created_at=2020-05-12T13:08:15Z,deleted=False,deleted_at=None,display_description='',display_name='',ec2_id=None,encryption_key_id=None,glance_metadata=<?>,group=<?>,group_id=None,host='centos7@lvm#lvm',id=ff682d50-2f29-45bd-a9ae-41a933ca5bd7,launched_at=None,metadata={},migration_status=None,multiattach=False,previous_status=None,project_id='973168b02ba046ec8ad7a56a4b28fb35',provider_auth=None,provider_geometry=None,provider_id=None,provider_location=None,replication_driver_data=None,replication_extended_status=None,replication_status=None,scheduled_at=2020-05-12T13:08:16Z,service_uuid=None,shared_targets=True,size=20,snapshot_id=None,snapshots=<?>,source_volid=None,status='downloading',terminated_at=None,updated_at=2020-05-12T13:08:16Z,user_id='775220a4ac234a878bdce88c2e3678b5',volume_attachment=<?>,volume_type=VolumeType(44cf1e15-4648-4db9-ab86-e0f80c62840f),volume_type_id=44cf1e15-4648-4db9-ab86-e0f80c62840f), 'request_spec': RequestSpec(CG_backend=<?>,availability_zones=['nova'],backup_id=None,cgsnapshot_id=None,consistencygroup_id=None,group_backend=<?>,group_id=None,image_id=33b99f7a-55ad-4205-b275-afc4fe70bd76,operation='create_volume',resource_backend=<?>,snapshot_id=None,source_replicaid=<?>,source_volid=None,volume=Volume(ff682d50-2f29-45bd-a9ae-41a933ca5bd7),volume_id=ff682d50-2f29-45bd-a9ae-41a933ca5bd7,volume_properties=VolumeProperties,volume_type=VolumeType(44cf1e15-4648-4db9-ab86-e0f80c62840f)), 'context': <cinder.context.RequestContext object at 0x7fb1a5e01610>}, 'provides': {'status': u'creating', 'image_location': (None, None), 'image_id': u'33b99f7a-55ad-4205-b275-afc4fe70bd76', 'volume_id': u'ff682d50-2f29-45bd-a9ae-41a933ca5bd7', 'volume_size': 20, 'image_service': <cinder.image.glance.GlanceImageService object at 0x7fb1a5de0a10>, 'image_meta': {u'status': u'active', u'file': u'/v2/images/33b99f7a-55ad-4205-b275-afc4fe70bd76/file', u'id': u'33b99f7a-55ad-4205-b275-afc4fe70bd76', u'name': u'cirros', u'tags': [], u'container_format': u'bare', u'created_at': datetime.datetime(2020, 5, 12, 12, 20, 18, tzinfo=<iso8601.Utc>), u'disk_format': u'qcow2', u'updated_at': datetime.datetime(2020, 5, 12, 12, 20, 19, tzinfo=<iso8601.Utc>), u'visibility': u'public', u'os_hash_algo': u'sha512', u'owner': u'fe075815291f47ad953af62fa77bc900', u'protected': False, u'os_hash_value': u'507ca3ef53a49145ede39d6cb7394bb40b5f419aec5abac496880112825cf177c15f49e35ac7c8c9a45d659598b71d0c59b93d85c79c2d54c69748bdeda2b0a5', u'min_ram': 0, u'checksum': u'52ba1c45042aa3688c09f303da283524', u'min_disk': 0, u'os_hidden': False, u'virtual_size': None, 'properties': {}, u'size': 273}, 'volume_name': u'volume-ff682d50-2f29-45bd-a9ae-41a933ca5bd7', 'type': 'image'}}
     |__Atom 'cinder.volume.flows.manager.create_volume.OnFailureRescheduleTask;volume:create' {'intention': 'EXECUTE', 'state': 'SUCCESS', 'requires': {'volume': Volume(_name_id=None,admin_metadata={},attach_status='detached',availability_zone='nova',bootable=False,cluster=<?>,cluster_name=None,consistencygroup=<?>,consistencygroup_id=None,created_at=2020-05-12T13:08:15Z,deleted=False,deleted_at=None,display_description='',display_name='',ec2_id=None,encryption_key_id=None,glance_metadata=<?>,group=<?>,group_id=None,host='centos7@lvm#lvm',id=ff682d50-2f29-45bd-a9ae-41a933ca5bd7,launched_at=None,metadata={},migration_status=None,multiattach=False,previous_status=None,project_id='973168b02ba046ec8ad7a56a4b28fb35',provider_auth=None,provider_geometry=None,provider_id=None,provider_location=None,replication_driver_data=None,replication_extended_status=None,replication_status=None,scheduled_at=2020-05-12T13:08:16Z,service_uuid=None,shared_targets=True,size=20,snapshot_id=None,snapshots=<?>,source_volid=None,status='downloading',terminated_at=None,updated_at=2020-05-12T13:08:16Z,user_id='775220a4ac234a878bdce88c2e3678b5',volume_attachment=<?>,volume_type=VolumeType(44cf1e15-4648-4db9-ab86-e0f80c62840f),volume_type_id=44cf1e15-4648-4db9-ab86-e0f80c62840f), 'filter_properties': {u'config_options': {}, u'request_spec': {u'backup_id': None, u'volume_id': u'ff682d50-2f29-45bd-a9ae-41a933ca5bd7', u'volume_properties': {u'status': u'creating', u'volume_type_id': u'44cf1e15-4648-4db9-ab86-e0f80c62840f', u'project_id': u'973168b02ba046ec8ad7a56a4b28fb35', u'user_id': u'775220a4ac234a878bdce88c2e3678b5', u'availability_zone': u'nova', u'reservations': [u'0533d767-624e-428b-bf80-ae84116a5e79', u'1ac5f595-9fb6-4e2d-b165-19c33fe51ca9', u'69b42361-28ac-410a-8afb-fdf0fe1665d7', u'b3aa244c-46ac-423d-973f-d4590b52126d'], u'multiattach': False, u'attach_status': u'detached', u'source_volid': None, u'cgsnapshot_id': None, u'metadata': {}, u'qos_specs': None, u'encryption_key_id': None, u'display_description': u'', u'snapshot_id': None, u'display_name': u'', u'group_id': None, u'consistencygroup_id': None, u'size': 20}, u'source_volid': None, u'cgsnapshot_id': None, u'volume': {u'migration_status': None, u'provider_id': None, u'availability_zone': u'nova', u'terminated_at': None, u'updated_at': None, u'provider_geometry': None, u'replication_extended_status': None, u'replication_status': None, u'snapshot_id': None, u'ec2_id': None, u'deleted_at': None, u'id': u'ff682d50-2f29-45bd-a9ae-41a933ca5bd7', u'size': 20, u'display_name': u'', u'display_description': u'', u'cluster_name': None, u'name_id': u'ff682d50-2f29-45bd-a9ae-41a933ca5bd7', u'volume_admin_metadata': [], u'project_id': u'973168b02ba046ec8ad7a56a4b28fb35', u'launched_at': None, u'scheduled_at': None, u'status': u'creating', u'volume_type_id': u'44cf1e15-4648-4db9-ab86-e0f80c62840f', u'multiattach': False, u'deleted': False, u'service_uuid': None, u'provider_location': None, u'volume_glance_metadata': [], u'host': None, u'consistencygroup_id': None, u'source_volid': None, u'provider_auth': None, u'previous_status': None, u'group_id': None, u'name': u'volume-ff682d50-2f29-45bd-a9ae-41a933ca5bd7', u'user_id': u'775220a4ac234a878bdce88c2e3678b5', u'bootable': False, u'shared_targets': True, u'attach_status': u'detached', u'volume_metadata': [], u'_name_id': None, u'encryption_key_id': None, u'replication_driver_data': None, u'metadata': {}, u'created_at': u'2020-05-12T13:08:15.000000'}, u'image_id': u'33b99f7a-55ad-4205-b275-afc4fe70bd76', u'availability_zones': [u'nova'], u'consistencygroup_id': None, u'volume_type': {u'name': u'iscsi', u'qos_specs_id': None, u'deleted': False, u'created_at': u'2020-05-12T12:20:50.000000', u'updated_at': None, u'extra_specs': {u'volume_backend_name': u'lvm'}, u'is_public': True, u'deleted_at': None, u'id': u'44cf1e15-4648-4db9-ab86-e0f80c62840f', u'projects': [], u'description': None}, u'snapshot_id': None, u'operation': u'create_volume', u'resource_properties': {u'status': u'creating', u'volume_type_id': u'44cf1e15-4648-4db9-ab86-e0f80c62840f', u'project_id': u'973168b02ba046ec8ad7a56a4b28fb35', u'user_id': u'775220a4ac234a878bdce88c2e3678b5', u'availability_zone': u'nova', u'reservations': [u'0533d767-624e-428b-bf80-ae84116a5e79', u'1ac5f595-9fb6-4e2d-b165-19c33fe51ca9', u'69b42361-28ac-410a-8afb-fdf0fe1665d7', u'b3aa244c-46ac-423d-973f-d4590b52126d'], u'multiattach': False, u'attach_status': u'detached', u'source_volid': None, u'cgsnapshot_id': None, u'metadata': {}, u'qos_specs': None, u'encryption_key_id': None, u'display_description': u'', u'snapshot_id': None, u'display_name': u'', u'group_id': None, u'consistencygroup_id': None, u'size': 20}, u'group_id': None}, u'user_id': u'775220a4ac234a878bdce88c2e3678b5', u'availability_zone': u'nova', u'volume_type': VolumeType(created_at=2020-05-12T12:20:50Z,deleted=False,deleted_at=None,description=None,extra_specs={volume_backend_name='lvm'},id=44cf1e15-4648-4db9-ab86-e0f80c62840f,is_public=True,name='iscsi',projects=[],qos_specs=<?>,qos_specs_id=None,updated_at=None), u'qos_specs': None, u'retry': {u'num_attempts': 1, u'backends': [u'centos7@lvm#lvm'], u'hosts': [u'centos7@lvm#lvm']}, u'metadata': {}, u'resource_type': VolumeType(created_at=2020-05-12T12:20:50Z,deleted=False,deleted_at=None,description=None,extra_specs={volume_backend_name='lvm'},id=44cf1e15-4648-4db9-ab86-e0f80c62840f,is_public=True,name='iscsi',projects=[],qos_specs=<?>,qos_specs_id=None,updated_at=None), u'size': 20}, 'context': <cinder.context.RequestContext object at 0x7fb1a5e01610>, 'request_spec': RequestSpec(CG_backend=<?>,availability_zones=['nova'],backup_id=None,cgsnapshot_id=None,consistencygroup_id=None,group_backend=<?>,group_id=None,image_id=33b99f7a-55ad-4205-b275-afc4fe70bd76,operation='create_volume',resource_backend=<?>,snapshot_id=None,source_replicaid=<?>,source_volid=None,volume=Volume(ff682d50-2f29-45bd-a9ae-41a933ca5bd7),volume_id=ff682d50-2f29-45bd-a9ae-41a933ca5bd7,volume_properties=VolumeProperties,volume_type=VolumeType(44cf1e15-4648-4db9-ab86-e0f80c62840f))}, 'provides': None}
        |__Atom 'cinder.volume.flows.manager.create_volume.ExtractVolumeRefTask;volume:create' {'intention': 'EXECUTE', 'state': 'SUCCESS', 'requires': {'volume': Volume(_name_id=None,admin_metadata={},attach_status='detached',availability_zone='nova',bootable=False,cluster=<?>,cluster_name=None,consistencygroup=<?>,consistencygroup_id=None,created_at=2020-05-12T13:08:15Z,deleted=False,deleted_at=None,display_description='',display_name='',ec2_id=None,encryption_key_id=None,glance_metadata=<?>,group=<?>,group_id=None,host='centos7@lvm#lvm',id=ff682d50-2f29-45bd-a9ae-41a933ca5bd7,launched_at=None,metadata={},migration_status=None,multiattach=False,previous_status=None,project_id='973168b02ba046ec8ad7a56a4b28fb35',provider_auth=None,provider_geometry=None,provider_id=None,provider_location=None,replication_driver_data=None,replication_extended_status=None,replication_status=None,scheduled_at=2020-05-12T13:08:16Z,service_uuid=None,shared_targets=True,size=20,snapshot_id=None,snapshots=<?>,source_volid=None,status='downloading',terminated_at=None,updated_at=2020-05-12T13:08:16Z,user_id='775220a4ac234a878bdce88c2e3678b5',volume_attachment=<?>,volume_type=VolumeType(44cf1e15-4648-4db9-ab86-e0f80c62840f),volume_type_id=44cf1e15-4648-4db9-ab86-e0f80c62840f), 'context': <cinder.context.RequestContext object at 0x7fb1a5e01610>}, 'provides': Volume(_name_id=None,admin_metadata={},attach_status='detached',availability_zone='nova',bootable=False,cluster=<?>,cluster_name=None,consistencygroup=<?>,consistencygroup_id=None,created_at=2020-05-12T13:08:15Z,deleted=False,deleted_at=None,display_description='',display_name='',ec2_id=None,encryption_key_id=None,glance_metadata=<?>,group=<?>,group_id=None,host='centos7@lvm#lvm',id=ff682d50-2f29-45bd-a9ae-41a933ca5bd7,launched_at=None,metadata={},migration_status=None,multiattach=False,previous_status=None,project_id='973168b02ba046ec8ad7a56a4b28fb35',provider_auth=None,provider_geometry=None,provider_id=None,provider_location=None,replication_driver_data=None,replication_extended_status=None,replication_status=None,scheduled_at=2020-05-12T13:08:16Z,service_uuid=None,shared_targets=True,size=20,snapshot_id=None,snapshots=<?>,source_volid=None,status='downloading',terminated_at=None,updated_at=2020-05-12T13:08:16Z,user_id='775220a4ac234a878bdce88c2e3678b5',volume_attachment=<?>,volume_type=VolumeType(44cf1e15-4648-4db9-ab86-e0f80c62840f),volume_type_id=44cf1e15-4648-4db9-ab86-e0f80c62840f)}
           |__Flow 'volume_create_manager': ImageCopyFailure: Failed to copy image to volume: qemu-img: Could not open '/var/lib/cinder/conversion/tmpyxMNYgcentos7@lvm': Image is not in qcow2 format
2020-05-12 09:08:20.621 17117 ERROR cinder.volume.manager Traceback (most recent call last):
2020-05-12 09:08:20.621 17117 ERROR cinder.volume.manager   File "/usr/lib/python2.7/site-packages/taskflow/engines/action_engine/executor.py", line 53, in _execute_task
2020-05-12 09:08:20.621 17117 ERROR cinder.volume.manager     result = task.execute(**arguments)
2020-05-12 09:08:20.621 17117 ERROR cinder.volume.manager   File "/usr/lib/python2.7/site-packages/cinder/volume/flows/manager/create_volume.py", line 980, in execute
2020-05-12 09:08:20.621 17117 ERROR cinder.volume.manager     **volume_spec)
2020-05-12 09:08:20.621 17117 ERROR cinder.volume.manager   File "/usr/lib/python2.7/site-packages/cinder/utils.py", line 818, in _wrapper
2020-05-12 09:08:20.621 17117 ERROR cinder.volume.manager     return r.call(f, *args, **kwargs)
2020-05-12 09:08:20.621 17117 ERROR cinder.volume.manager   File "/usr/lib/python2.7/site-packages/retrying.py", line 223, in call
2020-05-12 09:08:20.621 17117 ERROR cinder.volume.manager     return attempt.get(self._wrap_exception)
2020-05-12 09:08:20.621 17117 ERROR cinder.volume.manager   File "/usr/lib/python2.7/site-packages/retrying.py", line 261, in get
2020-05-12 09:08:20.621 17117 ERROR cinder.volume.manager     six.reraise(self.value[0], self.value[1], self.value[2])
2020-05-12 09:08:20.621 17117 ERROR cinder.volume.manager   File "/usr/lib/python2.7/site-packages/retrying.py", line 217, in call
2020-05-12 09:08:20.621 17117 ERROR cinder.volume.manager     attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
2020-05-12 09:08:20.621 17117 ERROR cinder.volume.manager   File "/usr/lib/python2.7/site-packages/cinder/volume/flows/manager/create_volume.py", line 880, in _create_from_image
2020-05-12 09:08:20.621 17117 ERROR cinder.volume.manager     image_service)
2020-05-12 09:08:20.621 17117 ERROR cinder.volume.manager   File "/usr/lib/python2.7/site-packages/cinder/volume/flows/manager/create_volume.py", line 771, in _create_from_image_cache_or_download
2020-05-12 09:08:20.621 17117 ERROR cinder.volume.manager     image_service
2020-05-12 09:08:20.621 17117 ERROR cinder.volume.manager   File "/usr/lib/python2.7/site-packages/cinder/volume/flows/manager/create_volume.py", line 584, in _create_from_image_download
2020-05-12 09:08:20.621 17117 ERROR cinder.volume.manager     image_service)
2020-05-12 09:08:20.621 17117 ERROR cinder.volume.manager   File "/usr/lib/python2.7/site-packages/cinder/volume/utils.py", line 1157, in copy_image_to_volume
2020-05-12 09:08:20.621 17117 ERROR cinder.volume.manager     raise exception.ImageCopyFailure(reason=ex.stderr)
2020-05-12 09:08:20.621 17117 ERROR cinder.volume.manager ImageCopyFailure: Failed to copy image to volume: qemu-img: Could not open '/var/lib/cinder/conversion/tmpyxMNYgcentos7@lvm': Image is not in qcow2 format
2020-05-12 09:08:20.621 17117 ERROR cinder.volume.manager 
2020-05-12 09:08:20.621 17117 ERROR cinder.volume.manager 
2020-05-12 09:08:20.629 17117 WARNING cinder.volume.manager [req-53a0e621-5faa-440e-9d4d-55560a68c432 775220a4ac234a878bdce88c2e3678b5 973168b02ba046ec8ad7a56a4b28fb35 - default default] Task 'cinder.volume.flows.manager.create_volume.CreateVolumeFromSpecTask;volume:create' (6742a7d5-7b21-426f-a497-6a0685acc07b) transitioned into state 'REVERTED' from state 'REVERTING'
2020-05-12 09:08:20.633 17117 WARNING cinder.volume.manager [req-53a0e621-5faa-440e-9d4d-55560a68c432 775220a4ac234a878bdce88c2e3678b5 973168b02ba046ec8ad7a56a4b28fb35 - default default] Task 'cinder.volume.flows.manager.create_volume.NotifyVolumeActionTask;volume:create, create.start' (e1259d68-37c0-4693-a809-9e14e16e3e1c) transitioned into state 'REVERTED' from state 'REVERTING'
2020-05-12 09:08:20.638 17117 WARNING cinder.volume.manager [req-53a0e621-5faa-440e-9d4d-55560a68c432 775220a4ac234a878bdce88c2e3678b5 973168b02ba046ec8ad7a56a4b28fb35 - default default] Task 'cinder.volume.flows.manager.create_volume.ExtractVolumeSpecTask;volume:create' (8fdc2a77-f95e-45a5-8a7e-1b40cd24a608) transitioned into state 'REVERTED' from state 'REVERTING'
2020-05-12 09:08:20.647 17117 ERROR cinder.volume.flows.manager.create_volume [req-53a0e621-5faa-440e-9d4d-55560a68c432 775220a4ac234a878bdce88c2e3678b5 973168b02ba046ec8ad7a56a4b28fb35 - default default] Volume ff682d50-2f29-45bd-a9ae-41a933ca5bd7: create failed
2020-05-12 09:08:20.649 17117 WARNING cinder.volume.manager [req-53a0e621-5faa-440e-9d4d-55560a68c432 775220a4ac234a878bdce88c2e3678b5 973168b02ba046ec8ad7a56a4b28fb35 - default default] Task 'cinder.volume.flows.manager.create_volume.OnFailureRescheduleTask;volume:create' (57078258-f02c-4153-ab65-ed88d64d68c4) transitioned into state 'REVERTED' from state 'REVERTING'
2020-05-12 09:08:20.652 17117 WARNING cinder.volume.manager [req-53a0e621-5faa-440e-9d4d-55560a68c432 775220a4ac234a878bdce88c2e3678b5 973168b02ba046ec8ad7a56a4b28fb35 - default default] Task 'cinder.volume.flows.manager.create_volume.ExtractVolumeRefTask;volume:create' (169ac7d9-5e0e-4820-b0c7-c91c46cdfc64) transitioned into state 'REVERTED' from state 'REVERTING'
2020-05-12 09:08:20.655 17117 WARNING cinder.volume.manager [req-53a0e621-5faa-440e-9d4d-55560a68c432 775220a4ac234a878bdce88c2e3678b5 973168b02ba046ec8ad7a56a4b28fb35 - default default] Flow 'volume_create_manager' (a6c16d09-bc3f-438c-84a5-9bddf7956f3e) transitioned into state 'REVERTED' from state 'RUNNING'
2020-05-12 09:08:20.663 17117 ERROR oslo_messaging.rpc.server [req-53a0e621-5faa-440e-9d4d-55560a68c432 775220a4ac234a878bdce88c2e3678b5 973168b02ba046ec8ad7a56a4b28fb35 - default default] Exception during message handling: ImageCopyFailure: Failed to copy image to volume: qemu-img: Could not open '/var/lib/cinder/conversion/tmpyxMNYgcentos7@lvm': Image is not in qcow2 format
2020-05-12 09:08:20.663 17117 ERROR oslo_messaging.rpc.server Traceback (most recent call last):
2020-05-12 09:08:20.663 17117 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/oslo_messaging/rpc/server.py", line 166, in _process_incoming
2020-05-12 09:08:20.663 17117 ERROR oslo_messaging.rpc.server     res = self.dispatcher.dispatch(message)
2020-05-12 09:08:20.663 17117 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/oslo_messaging/rpc/dispatcher.py", line 265, in dispatch
2020-05-12 09:08:20.663 17117 ERROR oslo_messaging.rpc.server     return self._do_dispatch(endpoint, method, ctxt, args)
2020-05-12 09:08:20.663 17117 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/oslo_messaging/rpc/dispatcher.py", line 194, in _do_dispatch
2020-05-12 09:08:20.663 17117 ERROR oslo_messaging.rpc.server     result = func(ctxt, **new_args)
2020-05-12 09:08:20.663 17117 ERROR oslo_messaging.rpc.server   File "<string>", line 2, in create_volume
2020-05-12 09:08:20.663 17117 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/cinder/objects/cleanable.py", line 208, in wrapper
2020-05-12 09:08:20.663 17117 ERROR oslo_messaging.rpc.server     result = f(*args, **kwargs)
2020-05-12 09:08:20.663 17117 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/cinder/volume/manager.py", line 749, in create_volume
2020-05-12 09:08:20.663 17117 ERROR oslo_messaging.rpc.server     _run_flow()
2020-05-12 09:08:20.663 17117 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/cinder/volume/manager.py", line 741, in _run_flow
2020-05-12 09:08:20.663 17117 ERROR oslo_messaging.rpc.server     flow_engine.run()
2020-05-12 09:08:20.663 17117 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/taskflow/engines/action_engine/engine.py", line 247, in run
2020-05-12 09:08:20.663 17117 ERROR oslo_messaging.rpc.server     for _state in self.run_iter(timeout=timeout):
2020-05-12 09:08:20.663 17117 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/taskflow/engines/action_engine/engine.py", line 340, in run_iter
2020-05-12 09:08:20.663 17117 ERROR oslo_messaging.rpc.server     failure.Failure.reraise_if_any(er_failures)
2020-05-12 09:08:20.663 17117 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/taskflow/types/failure.py", line 339, in reraise_if_any
2020-05-12 09:08:20.663 17117 ERROR oslo_messaging.rpc.server     failures[0].reraise()
2020-05-12 09:08:20.663 17117 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/taskflow/types/failure.py", line 346, in reraise
2020-05-12 09:08:20.663 17117 ERROR oslo_messaging.rpc.server     six.reraise(*self._exc_info)
2020-05-12 09:08:20.663 17117 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/taskflow/engines/action_engine/executor.py", line 53, in _execute_task
2020-05-12 09:08:20.663 17117 ERROR oslo_messaging.rpc.server     result = task.execute(**arguments)
2020-05-12 09:08:20.663 17117 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/cinder/volume/flows/manager/create_volume.py", line 980, in execute
2020-05-12 09:08:20.663 17117 ERROR oslo_messaging.rpc.server     **volume_spec)
2020-05-12 09:08:20.663 17117 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/cinder/utils.py", line 818, in _wrapper
2020-05-12 09:08:20.663 17117 ERROR oslo_messaging.rpc.server     return r.call(f, *args, **kwargs)
2020-05-12 09:08:20.663 17117 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/retrying.py", line 223, in call
2020-05-12 09:08:20.663 17117 ERROR oslo_messaging.rpc.server     return attempt.get(self._wrap_exception)
2020-05-12 09:08:20.663 17117 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/retrying.py", line 261, in get
2020-05-12 09:08:20.663 17117 ERROR oslo_messaging.rpc.server     six.reraise(self.value[0], self.value[1], self.value[2])
2020-05-12 09:08:20.663 17117 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/retrying.py", line 217, in call
2020-05-12 09:08:20.663 17117 ERROR oslo_messaging.rpc.server     attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
2020-05-12 09:08:20.663 17117 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/cinder/volume/flows/manager/create_volume.py", line 880, in _create_from_image
2020-05-12 09:08:20.663 17117 ERROR oslo_messaging.rpc.server     image_service)
2020-05-12 09:08:20.663 17117 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/cinder/volume/flows/manager/create_volume.py", line 771, in _create_from_image_cache_or_download
2020-05-12 09:08:20.663 17117 ERROR oslo_messaging.rpc.server     image_service
2020-05-12 09:08:20.663 17117 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/cinder/volume/flows/manager/create_volume.py", line 584, in _create_from_image_download
2020-05-12 09:08:20.663 17117 ERROR oslo_messaging.rpc.server     image_service)
2020-05-12 09:08:20.663 17117 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/cinder/volume/utils.py", line 1157, in copy_image_to_volume
2020-05-12 09:08:20.663 17117 ERROR oslo_messaging.rpc.server     raise exception.ImageCopyFailure(reason=ex.stderr)
2020-05-12 09:08:20.663 17117 ERROR oslo_messaging.rpc.server ImageCopyFailure: Failed to copy image to volume: qemu-img: Could not open '/var/lib/cinder/conversion/tmpyxMNYgcentos7@lvm': Image is not in qcow2 format
2020-05-12 09:08:20.663 17117 ERROR oslo_messaging.rpc.server 
2020-05-12 09:08:20.663 17117 ERROR oslo_messaging.rpc.server 
2020-05-12 09:08:22.906 17117 INFO cinder.volume.targets.iscsi [req-0d9f13ab-b320-4303-bed6-b3ac3c50e1a4 775220a4ac234a878bdce88c2e3678b5 973168b02ba046ec8ad7a56a4b28fb35 - default default] Skipping remove_export. No iscsi_target is presently exported for volume: ff682d50-2f29-45bd-a9ae-41a933ca5bd7
2020-05-12 09:08:24.165 17117 INFO cinder.volume.drivers.lvm [req-0d9f13ab-b320-4303-bed6-b3ac3c50e1a4 775220a4ac234a878bdce88c2e3678b5 973168b02ba046ec8ad7a56a4b28fb35 - default default] Successfully deleted volume: ff682d50-2f29-45bd-a9ae-41a933ca5bd7
2020-05-12 09:08:24.209 17117 WARNING cinder.quota [req-0d9f13ab-b320-4303-bed6-b3ac3c50e1a4 775220a4ac234a878bdce88c2e3678b5 973168b02ba046ec8ad7a56a4b28fb35 - default default] Deprecated: Default quota for resource: gigabytes_iscsi is set by the default quota flag: quota_gigabytes_iscsi, it is now deprecated. Please use the default quota class for default quota.
2020-05-12 09:08:24.211 17117 WARNING cinder.quota [req-0d9f13ab-b320-4303-bed6-b3ac3c50e1a4 775220a4ac234a878bdce88c2e3678b5 973168b02ba046ec8ad7a56a4b28fb35 - default default] Deprecated: Default quota for resource: volumes_iscsi is set by the default quota flag: quota_volumes_iscsi, it is now deprecated. Please use the default quota class for default quota.
2020-05-12 09:08:24.254 17117 WARNING py.warnings [req-0d9f13ab-b320-4303-bed6-b3ac3c50e1a4 775220a4ac234a878bdce88c2e3678b5 973168b02ba046ec8ad7a56a4b28fb35 - default default] /usr/lib64/python2.7/site-packages/sqlalchemy/orm/evaluator.py:99: SAWarning: Evaluating non-mapped column expression 'updated_at' onto ORM instances; this is a deprecated use case.  Please make use of the actual mapped columns in ORM-evaluated UPDATE / DELETE expressions.
  "UPDATE / DELETE expressions." % clause

2020-05-12 09:08:25.750 17117 INFO cinder.volume.manager [req-0d9f13ab-b320-4303-bed6-b3ac3c50e1a4 775220a4ac234a878bdce88c2e3678b5 973168b02ba046ec8ad7a56a4b28fb35 - default default] Deleted volume successfully.
2020-05-12 09:12:51.134 17117 WARNING stevedore.named [req-b126e6a6-19db-48f7-9c6e-ae73c137f61c 775220a4ac234a878bdce88c2e3678b5 973168b02ba046ec8ad7a56a4b28fb35 - default default] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
2020-05-12 09:12:51.135 17117 WARNING castellan.key_manager [req-b126e6a6-19db-48f7-9c6e-ae73c137f61c 775220a4ac234a878bdce88c2e3678b5 973168b02ba046ec8ad7a56a4b28fb35 - default default] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
2020-05-12 09:12:51.771 17117 INFO cinder.volume.flows.manager.create_volume [req-b126e6a6-19db-48f7-9c6e-ae73c137f61c 775220a4ac234a878bdce88c2e3678b5 973168b02ba046ec8ad7a56a4b28fb35 - default default] Volume b7f52705-416e-4dd2-9827-f7ca71aa53d7: being created as image with specification: {'status': u'creating', 'image_location': (None, None), 'volume_size': 1, 'volume_name': u'volume-b7f52705-416e-4dd2-9827-f7ca71aa53d7', 'image_id': u'33b99f7a-55ad-4205-b275-afc4fe70bd76', 'image_service': <cinder.image.glance.GlanceImageService object at 0x7fb1a4247610>, 'image_meta': {u'status': u'active', u'file': u'/v2/images/33b99f7a-55ad-4205-b275-afc4fe70bd76/file', u'id': u'33b99f7a-55ad-4205-b275-afc4fe70bd76', u'name': u'cirros', u'tags': [], u'container_format': u'bare', u'created_at': datetime.datetime(2020, 5, 12, 12, 20, 18, tzinfo=<iso8601.Utc>), u'disk_format': u'qcow2', u'updated_at': datetime.datetime(2020, 5, 12, 12, 20, 19, tzinfo=<iso8601.Utc>), u'visibility': u'public', u'os_hash_algo': u'sha512', u'owner': u'fe075815291f47ad953af62fa77bc900', u'protected': False, u'os_hash_value': u'507ca3ef53a49145ede39d6cb7394bb40b5f419aec5abac496880112825cf177c15f49e35ac7c8c9a45d659598b71d0c59b93d85c79c2d54c69748bdeda2b0a5', u'min_ram': 0, u'checksum': u'52ba1c45042aa3688c09f303da283524', u'min_disk': 0, u'os_hidden': False, u'virtual_size': None, 'properties': {}, u'size': 273}}
2020-05-12 09:12:51.842 17117 INFO cinder.image.image_utils [req-b126e6a6-19db-48f7-9c6e-ae73c137f61c 775220a4ac234a878bdce88c2e3678b5 973168b02ba046ec8ad7a56a4b28fb35 - default default] Image download 0.00 MB at 0.00 MB/s
2020-05-12 09:12:54.657 17117 ERROR cinder.volume.utils [req-b126e6a6-19db-48f7-9c6e-ae73c137f61c 775220a4ac234a878bdce88c2e3678b5 973168b02ba046ec8ad7a56a4b28fb35 - default default] Failed to copy image 33b99f7a-55ad-4205-b275-afc4fe70bd76 to volume: b7f52705-416e-4dd2-9827-f7ca71aa53d7: ProcessExecutionError: Unexpected error while running command.
Command: sudo cinder-rootwrap /etc/cinder/rootwrap.conf qemu-img convert -O raw -t none -f qcow2 /var/lib/cinder/conversion/tmpvyoEm5centos7@lvm /dev/mapper/cinder--volumes-volume--b7f52705--416e--4dd2--9827--f7ca71aa53d7
Exit code: 1
Stdout: u''
Stderr: u"qemu-img: Could not open '/var/lib/cinder/conversion/tmpvyoEm5centos7@lvm': Image is not in qcow2 format\n"
2020-05-12 09:12:54.657 17117 ERROR cinder.volume.utils Traceback (most recent call last):
2020-05-12 09:12:54.657 17117 ERROR cinder.volume.utils   File "/usr/lib/python2.7/site-packages/cinder/volume/utils.py", line 1152, in copy_image_to_volume
2020-05-12 09:12:54.657 17117 ERROR cinder.volume.utils     context, volume, image_service, image_id)
2020-05-12 09:12:54.657 17117 ERROR cinder.volume.utils   File "/usr/lib/python2.7/site-packages/cinder/volume/drivers/lvm.py", line 508, in copy_image_to_volume
2020-05-12 09:12:54.657 17117 ERROR cinder.volume.utils     size=volume['size'])
2020-05-12 09:12:54.657 17117 ERROR cinder.volume.utils   File "/usr/lib/python2.7/site-packages/cinder/image/image_utils.py", line 516, in fetch_to_raw
2020-05-12 09:12:54.657 17117 ERROR cinder.volume.utils     size=size, run_as_root=run_as_root)
2020-05-12 09:12:54.657 17117 ERROR cinder.volume.utils   File "/usr/lib/python2.7/site-packages/cinder/image/image_utils.py", line 596, in fetch_to_volume_format
2020-05-12 09:12:54.657 17117 ERROR cinder.volume.utils     run_as_root=run_as_root)
2020-05-12 09:12:54.657 17117 ERROR cinder.volume.utils   File "/usr/lib/python2.7/site-packages/cinder/image/image_utils.py", line 300, in convert_image
2020-05-12 09:12:54.657 17117 ERROR cinder.volume.utils     passphrase_file=passphrase_file)
2020-05-12 09:12:54.657 17117 ERROR cinder.volume.utils   File "/usr/lib/python2.7/site-packages/cinder/image/image_utils.py", line 244, in _convert_image
2020-05-12 09:12:54.657 17117 ERROR cinder.volume.utils     utils.execute(*cmd, run_as_root=run_as_root)
2020-05-12 09:12:54.657 17117 ERROR cinder.volume.utils   File "/usr/lib/python2.7/site-packages/cinder/utils.py", line 128, in execute
2020-05-12 09:12:54.657 17117 ERROR cinder.volume.utils     return processutils.execute(*cmd, **kwargs)
2020-05-12 09:12:54.657 17117 ERROR cinder.volume.utils   File "/usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py", line 424, in execute
2020-05-12 09:12:54.657 17117 ERROR cinder.volume.utils     cmd=sanitized_cmd)
2020-05-12 09:12:54.657 17117 ERROR cinder.volume.utils ProcessExecutionError: Unexpected error while running command.
2020-05-12 09:12:54.657 17117 ERROR cinder.volume.utils Command: sudo cinder-rootwrap /etc/cinder/rootwrap.conf qemu-img convert -O raw -t none -f qcow2 /var/lib/cinder/conversion/tmpvyoEm5centos7@lvm /dev/mapper/cinder--volumes-volume--b7f52705--416e--4dd2--9827--f7ca71aa53d7
2020-05-12 09:12:54.657 17117 ERROR cinder.volume.utils Exit code: 1
2020-05-12 09:12:54.657 17117 ERROR cinder.volume.utils Stdout: u''
2020-05-12 09:12:54.657 17117 ERROR cinder.volume.utils Stderr: u"qemu-img: Could not open '/var/lib/cinder/conversion/tmpvyoEm5centos7@lvm': Image is not in qcow2 format\n"
2020-05-12 09:12:54.657 17117 ERROR cinder.volume.utils 
2020-05-12 09:12:54.669 17117 WARNING cinder.volume.manager [req-b126e6a6-19db-48f7-9c6e-ae73c137f61c 775220a4ac234a878bdce88c2e3678b5 973168b02ba046ec8ad7a56a4b28fb35 - default default] Task 'cinder.volume.flows.manager.create_volume.CreateVolumeFromSpecTask;volume:create' (d77bd491-8a9c-4993-b4ab-fb4f23935aa4) transitioned into state 'FAILURE' from state 'RUNNING'
5 predecessors (most recent first):
  Atom 'cinder.volume.flows.manager.create_volume.NotifyVolumeActionTask;volume:create, create.start' {'intention': 'EXECUTE', 'state': 'SUCCESS', 'requires': {'volume': Volume(_name_id=None,admin_metadata={},attach_status='detached',availability_zone='nova',bootable=False,cluster=<?>,cluster_name=None,consistencygroup=<?>,consistencygroup_id=None,created_at=2020-05-12T13:12:50Z,deleted=False,deleted_at=None,display_description='',display_name='',ec2_id=None,encryption_key_id=None,glance_metadata=<?>,group=<?>,group_id=None,host='centos7@lvm#lvm',id=b7f52705-416e-4dd2-9827-f7ca71aa53d7,launched_at=None,metadata={},migration_status=None,multiattach=False,previous_status=None,project_id='973168b02ba046ec8ad7a56a4b28fb35',provider_auth=None,provider_geometry=None,provider_id=None,provider_location=None,replication_driver_data=None,replication_extended_status=None,replication_status=None,scheduled_at=2020-05-12T13:12:51Z,service_uuid=None,shared_targets=True,size=1,snapshot_id=None,snapshots=<?>,source_volid=None,status='downloading',terminated_at=None,updated_at=2020-05-12T13:12:51Z,user_id='775220a4ac234a878bdce88c2e3678b5',volume_attachment=<?>,volume_type=VolumeType(44cf1e15-4648-4db9-ab86-e0f80c62840f),volume_type_id=44cf1e15-4648-4db9-ab86-e0f80c62840f), 'context': <cinder.context.RequestContext object at 0x7fb1a4266bd0>}, 'provides': None}
  |__Atom 'cinder.volume.flows.manager.create_volume.ExtractVolumeSpecTask;volume:create' {'intention': 'EXECUTE', 'state': 'SUCCESS', 'requires': {'volume': Volume(_name_id=None,admin_metadata={},attach_status='detached',availability_zone='nova',bootable=False,cluster=<?>,cluster_name=None,consistencygroup=<?>,consistencygroup_id=None,created_at=2020-05-12T13:12:50Z,deleted=False,deleted_at=None,display_description='',display_name='',ec2_id=None,encryption_key_id=None,glance_metadata=<?>,group=<?>,group_id=None,host='centos7@lvm#lvm',id=b7f52705-416e-4dd2-9827-f7ca71aa53d7,launched_at=None,metadata={},migration_status=None,multiattach=False,previous_status=None,project_id='973168b02ba046ec8ad7a56a4b28fb35',provider_auth=None,provider_geometry=None,provider_id=None,provider_location=None,replication_driver_data=None,replication_extended_status=None,replication_status=None,scheduled_at=2020-05-12T13:12:51Z,service_uuid=None,shared_targets=True,size=1,snapshot_id=None,snapshots=<?>,source_volid=None,status='downloading',terminated_at=None,updated_at=2020-05-12T13:12:51Z,user_id='775220a4ac234a878bdce88c2e3678b5',volume_attachment=<?>,volume_type=VolumeType(44cf1e15-4648-4db9-ab86-e0f80c62840f),volume_type_id=44cf1e15-4648-4db9-ab86-e0f80c62840f), 'request_spec': RequestSpec(CG_backend=<?>,availability_zones=['nova'],backup_id=None,cgsnapshot_id=None,consistencygroup_id=None,group_backend=<?>,group_id=None,image_id=33b99f7a-55ad-4205-b275-afc4fe70bd76,operation='create_volume',resource_backend=<?>,snapshot_id=None,source_replicaid=<?>,source_volid=None,volume=Volume(b7f52705-416e-4dd2-9827-f7ca71aa53d7),volume_id=b7f52705-416e-4dd2-9827-f7ca71aa53d7,volume_properties=VolumeProperties,volume_type=VolumeType(44cf1e15-4648-4db9-ab86-e0f80c62840f)), 'context': <cinder.context.RequestContext object at 0x7fb1a4266bd0>}, 'provides': {'status': u'creating', 'image_location': (None, None), 'image_id': u'33b99f7a-55ad-4205-b275-afc4fe70bd76', 'volume_id': u'b7f52705-416e-4dd2-9827-f7ca71aa53d7', 'volume_size': 1, 'image_service': <cinder.image.glance.GlanceImageService object at 0x7fb1a4247610>, 'image_meta': {u'status': u'active', u'file': u'/v2/images/33b99f7a-55ad-4205-b275-afc4fe70bd76/file', u'id': u'33b99f7a-55ad-4205-b275-afc4fe70bd76', u'name': u'cirros', u'tags': [], u'container_format': u'bare', u'created_at': datetime.datetime(2020, 5, 12, 12, 20, 18, tzinfo=<iso8601.Utc>), u'disk_format': u'qcow2', u'updated_at': datetime.datetime(2020, 5, 12, 12, 20, 19, tzinfo=<iso8601.Utc>), u'visibility': u'public', u'os_hash_algo': u'sha512', u'owner': u'fe075815291f47ad953af62fa77bc900', u'protected': False, u'os_hash_value': u'507ca3ef53a49145ede39d6cb7394bb40b5f419aec5abac496880112825cf177c15f49e35ac7c8c9a45d659598b71d0c59b93d85c79c2d54c69748bdeda2b0a5', u'min_ram': 0, u'checksum': u'52ba1c45042aa3688c09f303da283524', u'min_disk': 0, u'os_hidden': False, u'virtual_size': None, 'properties': {}, u'size': 273}, 'volume_name': u'volume-b7f52705-416e-4dd2-9827-f7ca71aa53d7', 'type': 'image'}}
     |__Atom 'cinder.volume.flows.manager.create_volume.OnFailureRescheduleTask;volume:create' {'intention': 'EXECUTE', 'state': 'SUCCESS', 'requires': {'volume': Volume(_name_id=None,admin_metadata={},attach_status='detached',availability_zone='nova',bootable=False,cluster=<?>,cluster_name=None,consistencygroup=<?>,consistencygroup_id=None,created_at=2020-05-12T13:12:50Z,deleted=False,deleted_at=None,display_description='',display_name='',ec2_id=None,encryption_key_id=None,glance_metadata=<?>,group=<?>,group_id=None,host='centos7@lvm#lvm',id=b7f52705-416e-4dd2-9827-f7ca71aa53d7,launched_at=None,metadata={},migration_status=None,multiattach=False,previous_status=None,project_id='973168b02ba046ec8ad7a56a4b28fb35',provider_auth=None,provider_geometry=None,provider_id=None,provider_location=None,replication_driver_data=None,replication_extended_status=None,replication_status=None,scheduled_at=2020-05-12T13:12:51Z,service_uuid=None,shared_targets=True,size=1,snapshot_id=None,snapshots=<?>,source_volid=None,status='downloading',terminated_at=None,updated_at=2020-05-12T13:12:51Z,user_id='775220a4ac234a878bdce88c2e3678b5',volume_attachment=<?>,volume_type=VolumeType(44cf1e15-4648-4db9-ab86-e0f80c62840f),volume_type_id=44cf1e15-4648-4db9-ab86-e0f80c62840f), 'filter_properties': {u'config_options': {}, u'request_spec': {u'backup_id': None, u'volume_id': u'b7f52705-416e-4dd2-9827-f7ca71aa53d7', u'volume_properties': {u'status': u'creating', u'volume_type_id': u'44cf1e15-4648-4db9-ab86-e0f80c62840f', u'project_id': u'973168b02ba046ec8ad7a56a4b28fb35', u'user_id': u'775220a4ac234a878bdce88c2e3678b5', u'availability_zone': u'nova', u'reservations': [u'bc0ccde1-4769-47f4-961c-cf8521b6463b', u'25914557-e0f6-45c3-b4fc-ecafbf5de6ae', u'80c83b10-b7fb-4fdd-a308-73534bd8c5b7', u'851321da-3c0d-4cf9-967b-a5059a1fe066'], u'multiattach': False, u'attach_status': u'detached', u'source_volid': None, u'cgsnapshot_id': None, u'metadata': {}, u'qos_specs': None, u'encryption_key_id': None, u'display_description': u'', u'snapshot_id': None, u'display_name': u'', u'group_id': None, u'consistencygroup_id': None, u'size': 1}, u'source_volid': None, u'cgsnapshot_id': None, u'volume': {u'migration_status': None, u'provider_id': None, u'availability_zone': u'nova', u'terminated_at': None, u'updated_at': None, u'provider_geometry': None, u'replication_extended_status': None, u'replication_status': None, u'snapshot_id': None, u'ec2_id': None, u'deleted_at': None, u'id': u'b7f52705-416e-4dd2-9827-f7ca71aa53d7', u'size': 1, u'display_name': u'', u'display_description': u'', u'cluster_name': None, u'name_id': u'b7f52705-416e-4dd2-9827-f7ca71aa53d7', u'volume_admin_metadata': [], u'project_id': u'973168b02ba046ec8ad7a56a4b28fb35', u'launched_at': None, u'scheduled_at': None, u'status': u'creating', u'volume_type_id': u'44cf1e15-4648-4db9-ab86-e0f80c62840f', u'multiattach': False, u'deleted': False, u'service_uuid': None, u'provider_location': None, u'volume_glance_metadata': [], u'host': None, u'consistencygroup_id': None, u'source_volid': None, u'provider_auth': None, u'previous_status': None, u'group_id': None, u'name': u'volume-b7f52705-416e-4dd2-9827-f7ca71aa53d7', u'user_id': u'775220a4ac234a878bdce88c2e3678b5', u'bootable': False, u'shared_targets': True, u'attach_status': u'detached', u'volume_metadata': [], u'_name_id': None, u'encryption_key_id': None, u'replication_driver_data': None, u'metadata': {}, u'created_at': u'2020-05-12T13:12:50.000000'}, u'image_id': u'33b99f7a-55ad-4205-b275-afc4fe70bd76', u'availability_zones': [u'nova'], u'consistencygroup_id': None, u'volume_type': {u'name': u'iscsi', u'qos_specs_id': None, u'deleted': False, u'created_at': u'2020-05-12T12:20:50.000000', u'updated_at': None, u'extra_specs': {u'volume_backend_name': u'lvm'}, u'is_public': True, u'deleted_at': None, u'id': u'44cf1e15-4648-4db9-ab86-e0f80c62840f', u'projects': [], u'description': None}, u'snapshot_id': None, u'operation': u'create_volume', u'resource_properties': {u'status': u'creating', u'volume_type_id': u'44cf1e15-4648-4db9-ab86-e0f80c62840f', u'project_id': u'973168b02ba046ec8ad7a56a4b28fb35', u'user_id': u'775220a4ac234a878bdce88c2e3678b5', u'availability_zone': u'nova', u'reservations': [u'bc0ccde1-4769-47f4-961c-cf8521b6463b', u'25914557-e0f6-45c3-b4fc-ecafbf5de6ae', u'80c83b10-b7fb-4fdd-a308-73534bd8c5b7', u'851321da-3c0d-4cf9-967b-a5059a1fe066'], u'multiattach': False, u'attach_status': u'detached', u'source_volid': None, u'cgsnapshot_id': None, u'metadata': {}, u'qos_specs': None, u'encryption_key_id': None, u'display_description': u'', u'snapshot_id': None, u'display_name': u'', u'group_id': None, u'consistencygroup_id': None, u'size': 1}, u'group_id': None}, u'user_id': u'775220a4ac234a878bdce88c2e3678b5', u'availability_zone': u'nova', u'volume_type': VolumeType(created_at=2020-05-12T12:20:50Z,deleted=False,deleted_at=None,description=None,extra_specs={volume_backend_name='lvm'},id=44cf1e15-4648-4db9-ab86-e0f80c62840f,is_public=True,name='iscsi',projects=[],qos_specs=<?>,qos_specs_id=None,updated_at=None), u'qos_specs': None, u'retry': {u'num_attempts': 1, u'backends': [u'centos7@lvm#lvm'], u'hosts': [u'centos7@lvm#lvm']}, u'metadata': {}, u'resource_type': VolumeType(created_at=2020-05-12T12:20:50Z,deleted=False,deleted_at=None,description=None,extra_specs={volume_backend_name='lvm'},id=44cf1e15-4648-4db9-ab86-e0f80c62840f,is_public=True,name='iscsi',projects=[],qos_specs=<?>,qos_specs_id=None,updated_at=None), u'size': 1}, 'context': <cinder.context.RequestContext object at 0x7fb1a4266bd0>, 'request_spec': RequestSpec(CG_backend=<?>,availability_zones=['nova'],backup_id=None,cgsnapshot_id=None,consistencygroup_id=None,group_backend=<?>,group_id=None,image_id=33b99f7a-55ad-4205-b275-afc4fe70bd76,operation='create_volume',resource_backend=<?>,snapshot_id=None,source_replicaid=<?>,source_volid=None,volume=Volume(b7f52705-416e-4dd2-9827-f7ca71aa53d7),volume_id=b7f52705-416e-4dd2-9827-f7ca71aa53d7,volume_properties=VolumeProperties,volume_type=VolumeType(44cf1e15-4648-4db9-ab86-e0f80c62840f))}, 'provides': None}
        |__Atom 'cinder.volume.flows.manager.create_volume.ExtractVolumeRefTask;volume:create' {'intention': 'EXECUTE', 'state': 'SUCCESS', 'requires': {'volume': Volume(_name_id=None,admin_metadata={},attach_status='detached',availability_zone='nova',bootable=False,cluster=<?>,cluster_name=None,consistencygroup=<?>,consistencygroup_id=None,created_at=2020-05-12T13:12:50Z,deleted=False,deleted_at=None,display_description='',display_name='',ec2_id=None,encryption_key_id=None,glance_metadata=<?>,group=<?>,group_id=None,host='centos7@lvm#lvm',id=b7f52705-416e-4dd2-9827-f7ca71aa53d7,launched_at=None,metadata={},migration_status=None,multiattach=False,previous_status=None,project_id='973168b02ba046ec8ad7a56a4b28fb35',provider_auth=None,provider_geometry=None,provider_id=None,provider_location=None,replication_driver_data=None,replication_extended_status=None,replication_status=None,scheduled_at=2020-05-12T13:12:51Z,service_uuid=None,shared_targets=True,size=1,snapshot_id=None,snapshots=<?>,source_volid=None,status='downloading',terminated_at=None,updated_at=2020-05-12T13:12:51Z,user_id='775220a4ac234a878bdce88c2e3678b5',volume_attachment=<?>,volume_type=VolumeType(44cf1e15-4648-4db9-ab86-e0f80c62840f),volume_type_id=44cf1e15-4648-4db9-ab86-e0f80c62840f), 'context': <cinder.context.RequestContext object at 0x7fb1a4266bd0>}, 'provides': Volume(_name_id=None,admin_metadata={},attach_status='detached',availability_zone='nova',bootable=False,cluster=<?>,cluster_name=None,consistencygroup=<?>,consistencygroup_id=None,created_at=2020-05-12T13:12:50Z,deleted=False,deleted_at=None,display_description='',display_name='',ec2_id=None,encryption_key_id=None,glance_metadata=<?>,group=<?>,group_id=None,host='centos7@lvm#lvm',id=b7f52705-416e-4dd2-9827-f7ca71aa53d7,launched_at=None,metadata={},migration_status=None,multiattach=False,previous_status=None,project_id='973168b02ba046ec8ad7a56a4b28fb35',provider_auth=None,provider_geometry=None,provider_id=None,provider_location=None,replication_driver_data=None,replication_extended_status=None,replication_status=None,scheduled_at=2020-05-12T13:12:51Z,service_uuid=None,shared_targets=True,size=1,snapshot_id=None,snapshots=<?>,source_volid=None,status='downloading',terminated_at=None,updated_at=2020-05-12T13:12:51Z,user_id='775220a4ac234a878bdce88c2e3678b5',volume_attachment=<?>,volume_type=VolumeType(44cf1e15-4648-4db9-ab86-e0f80c62840f),volume_type_id=44cf1e15-4648-4db9-ab86-e0f80c62840f)}
           |__Flow 'volume_create_manager': ImageCopyFailure: Failed to copy image to volume: qemu-img: Could not open '/var/lib/cinder/conversion/tmpvyoEm5centos7@lvm': Image is not in qcow2 format
2020-05-12 09:12:54.669 17117 ERROR cinder.volume.manager Traceback (most recent call last):
2020-05-12 09:12:54.669 17117 ERROR cinder.volume.manager   File "/usr/lib/python2.7/site-packages/taskflow/engines/action_engine/executor.py", line 53, in _execute_task
2020-05-12 09:12:54.669 17117 ERROR cinder.volume.manager     result = task.execute(**arguments)
2020-05-12 09:12:54.669 17117 ERROR cinder.volume.manager   File "/usr/lib/python2.7/site-packages/cinder/volume/flows/manager/create_volume.py", line 980, in execute
2020-05-12 09:12:54.669 17117 ERROR cinder.volume.manager     **volume_spec)
2020-05-12 09:12:54.669 17117 ERROR cinder.volume.manager   File "/usr/lib/python2.7/site-packages/cinder/utils.py", line 818, in _wrapper
2020-05-12 09:12:54.669 17117 ERROR cinder.volume.manager     return r.call(f, *args, **kwargs)
2020-05-12 09:12:54.669 17117 ERROR cinder.volume.manager   File "/usr/lib/python2.7/site-packages/retrying.py", line 223, in call
2020-05-12 09:12:54.669 17117 ERROR cinder.volume.manager     return attempt.get(self._wrap_exception)
2020-05-12 09:12:54.669 17117 ERROR cinder.volume.manager   File "/usr/lib/python2.7/site-packages/retrying.py", line 261, in get
2020-05-12 09:12:54.669 17117 ERROR cinder.volume.manager     six.reraise(self.value[0], self.value[1], self.value[2])
2020-05-12 09:12:54.669 17117 ERROR cinder.volume.manager   File "/usr/lib/python2.7/site-packages/retrying.py", line 217, in call
2020-05-12 09:12:54.669 17117 ERROR cinder.volume.manager     attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
2020-05-12 09:12:54.669 17117 ERROR cinder.volume.manager   File "/usr/lib/python2.7/site-packages/cinder/volume/flows/manager/create_volume.py", line 880, in _create_from_image
2020-05-12 09:12:54.669 17117 ERROR cinder.volume.manager     image_service)
2020-05-12 09:12:54.669 17117 ERROR cinder.volume.manager   File "/usr/lib/python2.7/site-packages/cinder/volume/flows/manager/create_volume.py", line 771, in _create_from_image_cache_or_download
2020-05-12 09:12:54.669 17117 ERROR cinder.volume.manager     image_service
2020-05-12 09:12:54.669 17117 ERROR cinder.volume.manager   File "/usr/lib/python2.7/site-packages/cinder/volume/flows/manager/create_volume.py", line 584, in _create_from_image_download
2020-05-12 09:12:54.669 17117 ERROR cinder.volume.manager     image_service)
2020-05-12 09:12:54.669 17117 ERROR cinder.volume.manager   File "/usr/lib/python2.7/site-packages/cinder/volume/utils.py", line 1157, in copy_image_to_volume
2020-05-12 09:12:54.669 17117 ERROR cinder.volume.manager     raise exception.ImageCopyFailure(reason=ex.stderr)
2020-05-12 09:12:54.669 17117 ERROR cinder.volume.manager ImageCopyFailure: Failed to copy image to volume: qemu-img: Could not open '/var/lib/cinder/conversion/tmpvyoEm5centos7@lvm': Image is not in qcow2 format
2020-05-12 09:12:54.669 17117 ERROR cinder.volume.manager 
2020-05-12 09:12:54.669 17117 ERROR cinder.volume.manager 
2020-05-12 09:12:54.676 17117 WARNING cinder.volume.manager [req-b126e6a6-19db-48f7-9c6e-ae73c137f61c 775220a4ac234a878bdce88c2e3678b5 973168b02ba046ec8ad7a56a4b28fb35 - default default] Task 'cinder.volume.flows.manager.create_volume.CreateVolumeFromSpecTask;volume:create' (d77bd491-8a9c-4993-b4ab-fb4f23935aa4) transitioned into state 'REVERTED' from state 'REVERTING'
2020-05-12 09:12:54.680 17117 WARNING cinder.volume.manager [req-b126e6a6-19db-48f7-9c6e-ae73c137f61c 775220a4ac234a878bdce88c2e3678b5 973168b02ba046ec8ad7a56a4b28fb35 - default default] Task 'cinder.volume.flows.manager.create_volume.NotifyVolumeActionTask;volume:create, create.start' (f7db176f-25a3-40c6-9a1a-1bf327db1cef) transitioned into state 'REVERTED' from state 'REVERTING'
2020-05-12 09:12:54.684 17117 WARNING cinder.volume.manager [req-b126e6a6-19db-48f7-9c6e-ae73c137f61c 775220a4ac234a878bdce88c2e3678b5 973168b02ba046ec8ad7a56a4b28fb35 - default default] Task 'cinder.volume.flows.manager.create_volume.ExtractVolumeSpecTask;volume:create' (c6712414-d400-45a3-9c25-19f8b3bfc99e) transitioned into state 'REVERTED' from state 'REVERTING'
2020-05-12 09:12:54.694 17117 ERROR cinder.volume.flows.manager.create_volume [req-b126e6a6-19db-48f7-9c6e-ae73c137f61c 775220a4ac234a878bdce88c2e3678b5 973168b02ba046ec8ad7a56a4b28fb35 - default default] Volume b7f52705-416e-4dd2-9827-f7ca71aa53d7: create failed
2020-05-12 09:12:54.696 17117 WARNING cinder.volume.manager [req-b126e6a6-19db-48f7-9c6e-ae73c137f61c 775220a4ac234a878bdce88c2e3678b5 973168b02ba046ec8ad7a56a4b28fb35 - default default] Task 'cinder.volume.flows.manager.create_volume.OnFailureRescheduleTask;volume:create' (91bb11b0-d986-40a5-90ab-d7ec0776c062) transitioned into state 'REVERTED' from state 'REVERTING'
2020-05-12 09:12:54.700 17117 WARNING cinder.volume.manager [req-b126e6a6-19db-48f7-9c6e-ae73c137f61c 775220a4ac234a878bdce88c2e3678b5 973168b02ba046ec8ad7a56a4b28fb35 - default default] Task 'cinder.volume.flows.manager.create_volume.ExtractVolumeRefTask;volume:create' (3c7a49d8-40b8-4a81-a271-a731b517c576) transitioned into state 'REVERTED' from state 'REVERTING'
2020-05-12 09:12:54.703 17117 WARNING cinder.volume.manager [req-b126e6a6-19db-48f7-9c6e-ae73c137f61c 775220a4ac234a878bdce88c2e3678b5 973168b02ba046ec8ad7a56a4b28fb35 - default default] Flow 'volume_create_manager' (34f83571-74fa-45b3-a87e-bbf0854a2271) transitioned into state 'REVERTED' from state 'RUNNING'
2020-05-12 09:12:54.709 17117 ERROR oslo_messaging.rpc.server [req-b126e6a6-19db-48f7-9c6e-ae73c137f61c 775220a4ac234a878bdce88c2e3678b5 973168b02ba046ec8ad7a56a4b28fb35 - default default] Exception during message handling: ImageCopyFailure: Failed to copy image to volume: qemu-img: Could not open '/var/lib/cinder/conversion/tmpvyoEm5centos7@lvm': Image is not in qcow2 format
2020-05-12 09:12:54.709 17117 ERROR oslo_messaging.rpc.server Traceback (most recent call last):
2020-05-12 09:12:54.709 17117 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/oslo_messaging/rpc/server.py", line 166, in _process_incoming
2020-05-12 09:12:54.709 17117 ERROR oslo_messaging.rpc.server     res = self.dispatcher.dispatch(message)
2020-05-12 09:12:54.709 17117 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/oslo_messaging/rpc/dispatcher.py", line 265, in dispatch
2020-05-12 09:12:54.709 17117 ERROR oslo_messaging.rpc.server     return self._do_dispatch(endpoint, method, ctxt, args)
2020-05-12 09:12:54.709 17117 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/oslo_messaging/rpc/dispatcher.py", line 194, in _do_dispatch
2020-05-12 09:12:54.709 17117 ERROR oslo_messaging.rpc.server     result = func(ctxt, **new_args)
2020-05-12 09:12:54.709 17117 ERROR oslo_messaging.rpc.server   File "<string>", line 2, in create_volume
2020-05-12 09:12:54.709 17117 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/cinder/objects/cleanable.py", line 208, in wrapper
2020-05-12 09:12:54.709 17117 ERROR oslo_messaging.rpc.server     result = f(*args, **kwargs)
2020-05-12 09:12:54.709 17117 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/cinder/volume/manager.py", line 749, in create_volume
2020-05-12 09:12:54.709 17117 ERROR oslo_messaging.rpc.server     _run_flow()
2020-05-12 09:12:54.709 17117 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/cinder/volume/manager.py", line 741, in _run_flow
2020-05-12 09:12:54.709 17117 ERROR oslo_messaging.rpc.server     flow_engine.run()
2020-05-12 09:12:54.709 17117 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/taskflow/engines/action_engine/engine.py", line 247, in run
2020-05-12 09:12:54.709 17117 ERROR oslo_messaging.rpc.server     for _state in self.run_iter(timeout=timeout):
2020-05-12 09:12:54.709 17117 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/taskflow/engines/action_engine/engine.py", line 340, in run_iter
2020-05-12 09:12:54.709 17117 ERROR oslo_messaging.rpc.server     failure.Failure.reraise_if_any(er_failures)
2020-05-12 09:12:54.709 17117 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/taskflow/types/failure.py", line 339, in reraise_if_any
2020-05-12 09:12:54.709 17117 ERROR oslo_messaging.rpc.server     failures[0].reraise()
2020-05-12 09:12:54.709 17117 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/taskflow/types/failure.py", line 346, in reraise
2020-05-12 09:12:54.709 17117 ERROR oslo_messaging.rpc.server     six.reraise(*self._exc_info)
2020-05-12 09:12:54.709 17117 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/taskflow/engines/action_engine/executor.py", line 53, in _execute_task
2020-05-12 09:12:54.709 17117 ERROR oslo_messaging.rpc.server     result = task.execute(**arguments)
2020-05-12 09:12:54.709 17117 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/cinder/volume/flows/manager/create_volume.py", line 980, in execute
2020-05-12 09:12:54.709 17117 ERROR oslo_messaging.rpc.server     **volume_spec)
2020-05-12 09:12:54.709 17117 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/cinder/utils.py", line 818, in _wrapper
2020-05-12 09:12:54.709 17117 ERROR oslo_messaging.rpc.server     return r.call(f, *args, **kwargs)
2020-05-12 09:12:54.709 17117 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/retrying.py", line 223, in call
2020-05-12 09:12:54.709 17117 ERROR oslo_messaging.rpc.server     return attempt.get(self._wrap_exception)
2020-05-12 09:12:54.709 17117 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/retrying.py", line 261, in get
2020-05-12 09:12:54.709 17117 ERROR oslo_messaging.rpc.server     six.reraise(self.value[0], self.value[1], self.value[2])
2020-05-12 09:12:54.709 17117 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/retrying.py", line 217, in call
2020-05-12 09:12:54.709 17117 ERROR oslo_messaging.rpc.server     attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
2020-05-12 09:12:54.709 17117 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/cinder/volume/flows/manager/create_volume.py", line 880, in _create_from_image
2020-05-12 09:12:54.709 17117 ERROR oslo_messaging.rpc.server     image_service)
2020-05-12 09:12:54.709 17117 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/cinder/volume/flows/manager/create_volume.py", line 771, in _create_from_image_cache_or_download
2020-05-12 09:12:54.709 17117 ERROR oslo_messaging.rpc.server     image_service
2020-05-12 09:12:54.709 17117 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/cinder/volume/flows/manager/create_volume.py", line 584, in _create_from_image_download
2020-05-12 09:12:54.709 17117 ERROR oslo_messaging.rpc.server     image_service)
2020-05-12 09:12:54.709 17117 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/cinder/volume/utils.py", line 1157, in copy_image_to_volume
2020-05-12 09:12:54.709 17117 ERROR oslo_messaging.rpc.server     raise exception.ImageCopyFailure(reason=ex.stderr)
2020-05-12 09:12:54.709 17117 ERROR oslo_messaging.rpc.server ImageCopyFailure: Failed to copy image to volume: qemu-img: Could not open '/var/lib/cinder/conversion/tmpvyoEm5centos7@lvm': Image is not in qcow2 format
2020-05-12 09:12:54.709 17117 ERROR oslo_messaging.rpc.server 
2020-05-12 09:12:54.709 17117 ERROR oslo_messaging.rpc.server 
2020-05-12 09:12:57.632 17117 INFO cinder.volume.targets.iscsi [req-a4f47868-df45-4853-b5a5-761f3fe44e52 775220a4ac234a878bdce88c2e3678b5 973168b02ba046ec8ad7a56a4b28fb35 - default default] Skipping remove_export. No iscsi_target is presently exported for volume: b7f52705-416e-4dd2-9827-f7ca71aa53d7
2020-05-12 09:12:58.787 17117 INFO cinder.volume.drivers.lvm [req-a4f47868-df45-4853-b5a5-761f3fe44e52 775220a4ac234a878bdce88c2e3678b5 973168b02ba046ec8ad7a56a4b28fb35 - default default] Successfully deleted volume: b7f52705-416e-4dd2-9827-f7ca71aa53d7
2020-05-12 09:13:00.241 17117 INFO cinder.volume.manager [req-a4f47868-df45-4853-b5a5-761f3fe44e52 775220a4ac234a878bdce88c2e3678b5 973168b02ba046ec8ad7a56a4b28fb35 - default default] Deleted volume successfully.
